

services:
  web_homelaurechips:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db_homelaurechips
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - homelaurechips_network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homelaurechips.rule=Host(`hlc.digitaleflex.com`)"
      - "traefik.http.routers.homelaurechips.entrypoints=websecure"
      - "traefik.http.routers.homelaurechips.tls.certresolver=letsencrypt"
      - "traefik.http.services.homelaurechips.loadbalancer.server.port=80" 
      - "traefik.http.routers.homelaurechips.service=homelaurechips"
      - "traefik.http.services.homelaurechips.loadbalancer.passhostheader=true"
      - "traefik.http.routers.homelaurechips.tls.options=default"
      - "traefik.http.middlewares.secHeaders.headers.sslRedirect=true"
      - "traefik.http.middlewares.secHeaders.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.secHeaders.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.secHeaders.headers.stsPreload=true"
      - "traefik.http.middlewares.secHeaders.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.secHeaders.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.secHeaders.headers.browserXssFilter=true"
      - "traefik.http.middlewares.secHeaders.headers.referrerPolicy=strict-origin-when-cross-origin"
      - "traefik.http.middlewares.secHeaders.headers.permissionsPolicy=camera=(), microphone=(), geolocation=()"
      - "traefik.http.routers.homelaurechips.middlewares=secHeaders"

  db_homelaurechips:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - homelaurechips_network

volumes:
  db_data:

networks:
  homelaurechips_network:
    driver: bridge
  proxy:
    external: true
